#!/usr/bin/env bash
# This script transfer a file to your server

PATH_TO_SSH_KEY=$4
PATH_TO_FILE=$1
IP=$2
USERNAME=$3

if [[ $# -lt 3 ]];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else 
  scp -r -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP":~
fi
