#!/usr/bin/env bash
# this script install nginx inside the server and configuret it.
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
