#!/usr/bin/env bash
# this script install nginx inside the server and configuret it.
apt-get update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
line="rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "42i $line" /etc/nginx/sites-available/default
service nginx restart
