#!/usr/bin/env bash
# this is a comment
day=$(date '+%d')
month=$(date '+%m')
year=$(date '+%Y')
mysqldump -u root -p "$1" --all-databases > backup.sql
tar -zcvf "$day-$month-$year.tar.gz" backup.sql
