#!/usr/bin/env bash
# this script install nginx inside the server and configuret it.
apt-get -y update
echo "server {
         listen 80 default_server;

        listen [::]:80 default_server ipv6only=on;

        root /usr/share/nginx/html;
        index index.html index.htm;

        # Make site accessible from http://localhost/
        server_name localhost;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
                # Uncomment to enable naxsi on this location
                # include /etc/nginx/naxsi.rules
		}
	}" > /etc/nginx/sites-enabled/default
service nginx restart
