#!/usr/bin/env bash
# bash script that dont want to died
echo "$BASHPID" >> /var/run/holbertonscript.pid

hate() {
  echo "I hate the kill command"
  trap - SIGTERM
  rm /var/run/holbertonscript.pid
  exit
}

love() {
  echo "Y U no love me?!"
  trap - SIGINT
  exit
}

del() {
  rm /var/run/holbertonscript.pid
  trap - SIGQUIt
}

while true
do
  echo "To infinity and beyond"
  trap hate SIGTERM
  trap love SIGINT
done
