#!/usr/bin/env bash
# manage other process with the flags
f="/var/run/my_process.pid"

termi() {
  trap - SIGTERM
  exit
}

sta() {
  
  echo "$BASHPID" >> "$f"
  ./manage_my_process &
}

sto() {
  
  rm $f
  trap termi SIGTERM
  pkill $BASHPID
}

if [ $# != 0 ]
then
  case "$1" in
    start)
      sta
      echo "manage_my_process started"
      ;;
    stop)
      echo "manage_my_process stopped"
      sto
      ;;
    restart)
      echo "manage_my_process restarted"
      sto
      sta
      ;;
    *)
    echo "Usage: manage_my_process {start|stop|restart}"
  esac
else
  echo "Usage: manage_my_process {start|stop|restart}"
fi
