#!/usr/bin/env bash
# This script is displaying "Holberton School" 9 times and the hi in the 9th
n=1
while [ $n -le 9 ]
do
  if [ $n == 9 ]
  then
    echo "Hi"
    echo "Holberton School"
  fi
  echo "Holberton School"
  n=$(( n + 1))
done
