#!/usr/bin/env bash
# This script is displaying "Holberton School" 9 times and the hi in the 9th
n=1
while [ $n -le 10 ]
do
  if [ $n == 9 ]
  then
    echo "Holberton School"
    echo "Hi"
  else
    echo "Holberton School"
  fi
  n=$(( n + 1))
done
