#!/usr/bin/env bash
# displays "Holberton School, bad luck and good luck 1 time"
n=1
while [ $n -le 10 ]
do
  if [ $n == 4 ]
  then
    echo "bad luck"
  elif [ $n == 8 ]
  then
    echo "good luck"
  else
    echo "Holberton School"
  fi
  n=$(( n + 1))
done
