#!/usr/bin/env bash
# bad luck from China for the 4th loop iteration Japan for the 9th and Italy for the 17th
n=1
while [ $n -le 20 ]
do
  case $n in
    4)
    echo $n
    echo "bad luck from China"
    ;;
    9)
    echo $n
    echo "bad luck from Japan"
    ;;
    17)
    echo $n
    echo "bad luck from Italy"
    ;;
    *)
    echo $n
esac
  n=$(( n + 1))
done
