#!/usr/bin/env bash
# Run Nginx as Nginx
chown nginx:nginx /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
pkill -9 apache2
sed 's/80/8080/g' /etc/nginx/sites-available/default
service nginx restart
